my_project:
  target: dev
  outputs:
    dev:
      account: fs13598.ap-northeast-1.aws
      database: DBT_DB
      password: Mikoto3510!
      role: ACCOUNTADMIN
      schema: DBT_SCHEMA
      type: snowflake
      user: MIKOTOHASHIMOTO
      warehouse: DBT_WH